[workspace]
members = [
  "examples/hello/main.rs",
  "examples/hey/main.rs",
  "examples/gcd/main.rs",
]

[package]
name = "wasm-noodles"
version = "0.1.0"
edition = "2021"

[dependencies]
wasmtime = "27.0.0"
